### ISSUE TITLE
Investigation of steady state

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DynamicClasses#6]
One possible approach to check if a simulation has arrived at a steady state:

- From simulation: measure $\pi$.
- Generate state space from $\pi$
- Generate theoretic matrix $Q$ from state space.
- Verify numerical if $\pi Q \approx 0$.

**Comment by geraintpalmer** [comment]
+ Sojourn time Markov chain model -- people are getting 'stuck' in the queue (swapping back and forth between classes), even though state Markov chain might bet steady state. Investigate:
  + consider hitting times?
  + run simulations long enough to see is mean sojourn time flattens off

**Comment by geraintpalmer** [comment]
Adressed with the Augmented Dickey-Fuller test on simulation state time series.
